# Copyright (c) 2025, Machete Authors
"""Replay instruction row layout."""

INSTR_OP_IDX = 0
INSTR_TILE_01 = 1
INSTR_TILE_23 = 2
INSTR_BARRIER_META_IDX = 3
INSTR_RANGE_END = 4
INSTR_RANGE_META = INSTR_OP_IDX
INSTR_PADDING = INSTR_RANGE_END
INSTRUCTION_WORDS = 5
INSTRUCTION_ROW_BYTES = INSTRUCTION_WORDS * 4


__all__ = [
    "INSTR_BARRIER_META_IDX",
    "INSTR_OP_IDX",
    "INSTR_PADDING",
    "INSTR_RANGE_META",
    "INSTR_RANGE_END",
    "INSTR_TILE_01",
    "INSTR_TILE_23",
    "INSTRUCTION_ROW_BYTES",
    "INSTRUCTION_WORDS",
]
