# Copyright (c) 2025, Machete Authors
"""Replay instruction row layout."""

INSTR_OP_IDX = 0
INSTR_TILE_0 = 1
INSTR_TILE_1 = 2
INSTR_TILE_2 = 3
INSTR_TILE_3 = 4
INSTR_TILE_4 = 5
INSTR_BARRIER_META_IDX = 6
INSTR_PADDING = 7
INSTRUCTION_WORDS = 8
INSTRUCTION_ROW_BYTES = INSTRUCTION_WORDS * 4


__all__ = [
    "INSTR_BARRIER_META_IDX",
    "INSTR_OP_IDX",
    "INSTR_PADDING",
    "INSTR_TILE_0",
    "INSTR_TILE_1",
    "INSTR_TILE_2",
    "INSTR_TILE_3",
    "INSTR_TILE_4",
    "INSTRUCTION_ROW_BYTES",
    "INSTRUCTION_WORDS",
]
